default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432   # usually same for 16
  username: postgres
  password: 12345678
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bugMS_development

test:
  <<: *default
  database: bugMS_test

production:
  <<: *default
  database: bugMS_production
