default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PGUSER") { "postgres" } %>
  password: <%= ENV.fetch("PGPASSWORD") { "12345678" } %>
  host: <%= ENV.fetch("PGHOST") { "localhost" } %>

development:
  <<: *default
  database: bugMS_development

test:
  <<: *default
  database: bugMS_test

production:
  <<: *default
  database: bugMS_production
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
